AllCops:
  TargetRubyVersion: 2.6.2
  EnabledByDefault: true

Metrics/LineLength:
  Max: 120

Style/SignalException:
  Enabled: false
Lint/UnreachableCode:
  Description: 'Unreachable code.'
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/*
    - spec/**/*spec.rb

Metrics/BlockLength:
  Exclude:
    - spec/*
    - spec/**/*spec.rb
